/**
 * Every user-facing string in the application. Components read from here and never write copy inline,
 * so wording can be reviewed in one place. Functions are used where a sentence carries a value.
 */
export const copy = {
  appName: "Delivery Metrics",
  skipToContent: "Skip to main content",

  common: {
    loading: "Loading",
    retry: "Try again",
    notAvailable: "No data",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving",
    close: "Close",
    viewAsTable: "View as table",
    backToRepos: "Back to repositories",
    requestFailed: (status: number) => `The request failed with status ${status}.`,
    networkFailed: "The dashboard could not reach its API. Check that the API is running and try again.",
    errorTitle: "Something went wrong",
    opensInNewTab: "(opens in a new tab)",
  },

  theme: {
    toLight: "Switch to light theme",
    toDark: "Switch to dark theme",
    light: "Light",
    dark: "Dark",
  },

  auth: {
    checking: "Checking your GitHub session",
    signInTitle: "Sign in to see your delivery metrics",
    signInBody: "The dashboard reads pull requests and deploy runs from GitHub using your own access.",
    signInButton: "Sign in with GitHub",
    ghCliTitle: "The GitHub CLI is not signed in",
    ghCliBody: "This dashboard uses the GitHub CLI session on the machine running the API.",
    ghCliInstruction: "Run the command below in a terminal, then reload this page.",
    ghCliCommand: "gh auth login",
    reload: "Reload",
    signOut: "Sign out",
    signedInAs: (login: string) => `Signed in as ${login}`,
    avatarAlt: (login: string) => `${login} avatar`,
  },

  nav: {
    label: "Main",
    repositories: "Repositories",
  },

  repos: {
    title: "Repositories",
    lede: "Add the repositories you want to measure. Each one is crawled from GitHub in the background.",
    addTitle: "Add a repository",
    repoLabel: "Repository",
    repoHint: "Use owner/name, for example acme/widgets, or paste a github.com link.",
    repoPlaceholder: "acme/widgets",
    workflowLabel: "Deploy workflow (optional)",
    workflowHint: "Workflow file names whose successful runs count as deployments. Separate several with commas.",
    workflowPlaceholder: "deploy.yml",
    branchLabel: "Deploy branch (optional)",
    branchHint: "Only runs on this branch count as production deployments.",
    branchPlaceholder: "main",
    addButton: "Add repository",
    adding: "Adding",
    added: (name: string) => `${name} was added and its first crawl has started.`,
    listTitle: "Your repositories",
    emptyTitle: "No repositories yet",
    emptyBody: "Add a repository above to start collecting pull request and deployment history.",
    pullRequests: "Pull requests",
    deployRuns: "Deploy runs",
    lastCrawled: "Last crawled",
    neverCrawled: "Not yet crawled",
    deployConfig: "Deploys",
    noDeployWorkflow: "No deploy workflow configured",
    deployDescription: (workflows: string, branch: string) => `${workflows} on ${branch}`,
    status: {
      idle: "Up to date",
      crawling: "Crawling",
      failed: "Crawl failed",
    },
    crawlingFallback: "Starting crawl",
    recrawl: "Re-crawl",
    fullRecrawl: "Full re-crawl",
    configure: "Configure deploy",
    remove: "Remove",
    confirmRemove: (name: string) => `Remove ${name} and all of its collected history?`,
    selectForCompare: (name: string) => `Select ${name} for comparison`,
    compareButton: "Compare",
    compareHint: "Select two to four repositories to compare them side by side.",
    compareSelected: (count: number) => `${count} selected`,
    openDashboard: (name: string) => `Open the dashboard for ${name}`,
  },

  configure: {
    title: (name: string) => `Deploy settings for ${name}`,
    workflowsLegend: "Deploy workflows",
    workflowsHint: "Successful runs of the ticked workflows count as deployments.",
    loadingWorkflows: "Loading workflows",
    noWorkflows: "This repository has no GitHub Actions workflows.",
    branchLabel: "Deploy branch",
    saved: "Deploy settings saved. Re-crawl to pick up runs from newly ticked workflows.",
  },

  range: {
    legend: "Date range",
    from: "From",
    to: "To",
    presetsLabel: "Presets",
    allActive: "Period all were active",
    allTime: "All time",
    last90: "Last 90 days",
    last30: "Last 30 days",
    includeBots: "Include bots",
    includeBotsHint: "Count pull requests opened by automation accounts such as dependency updaters.",
  },

  dora: {
    title: "DORA measures",
    lede: "The four measures of software delivery performance, each placed in a performance band.",
    band: {
      elite: "Elite",
      high: "High",
      medium: "Medium",
      low: "Low",
    },
    bandLabel: (band: string) => `${band} performance band`,
    notMeasured: "Not measured",
    deploymentFrequency: "Deployment frequency",
    deploymentFrequencyDefinition: "How often a successful deploy reaches production.",
    perWeek: (value: string) => `${value} per week`,
    leadTime: "Lead time for changes",
    leadTimeDefinition: "Median time from a change's first commit to its successful deploy.",
    changeFailure: "Change failure rate",
    changeFailureDefinition: "Share of production deploys that failed.",
    timeToRestore: "Time to restore",
    timeToRestoreDefinition: "Median time from a failed deploy to the next successful one.",
    reasons: {
      noWorkflow: "No deploy workflow is configured for this repository.",
      noRuns: (branch: string) => `No completed deploy runs on ${branch} in this range.`,
      noShipped: "No merged pull request was shipped by an observed deploy in this range.",
      noFailures: "No failed deploys in this range, so there was nothing to restore.",
      noRecovery: "No failed deploy has been followed by a successful one yet.",
    },
    deploysCount: (total: number, weeks: number) => `${total} successful deploys over ${weeks} weeks`,
    leadCount: (count: number) => `Across ${count} shipped pull requests`,
    failureCount: (failed: number, total: number) => `${failed} of ${total} deploys failed`,
    restoreCount: (count: number) => `Across ${count} recoveries`,
  },

  flow: {
    title: "Pull request flow",
    lede: "How work moves from first commit to merge. Medians are used so a few outliers do not dominate.",
    merged: "PRs merged",
    mergedHint: (opened: number) => `${opened} opened in this range`,
    coding: "Coding time",
    codingHint: "Median first commit to PR opened",
    firstReview: "Time to first review",
    firstReviewHint: "Median ready for review to first review",
    openToMerge: "Open to merge",
    openToMergeHint: (p75: string) => `Median, 75th percentile ${p75}`,
    reviewed: "Reviewed",
    reviewedHint: "Share of merged PRs reviewed by someone else",
    selfMerged: "Self-merged",
    selfMergedHint: "Share of merged PRs merged by their author",
    perAuthorWeek: "Merged per author-week",
    perAuthorWeekHint: "Merged PRs divided by weekly active authors",
  },

  charts: {
    weekStarting: "Week starting",
    hours: "Hours",
    share: "Share of merged PRs",
    count: "Count",
    openedVsMerged: {
      title: "Pull requests opened and merged",
      subtitle: "Weekly count of pull requests opened against those merged.",
      opened: "Opened",
      merged: "Merged",
    },
    weeklyOpenToMerge: {
      title: "Median open to merge",
      subtitle: "The median time a pull request merged that week spent open, in hours.",
      series: "Median open to merge",
    },
    deploys: {
      title: "Deploys and failures",
      subtitle: "Weekly count of successful and failed production deploys.",
      deploys: "Successful deploys",
      failures: "Failed deploys",
    },
    stages: {
      title: "Cycle time by stage",
      subtitle: "Mean hours per stage for pull requests merged each week. Means are shown because they add up to the whole bar.",
      coding: "Coding",
      waitingForReview: "Waiting for review",
      inReview: "In review",
      toMerge: "To merge",
      stage: "Stage",
      meanHours: "Mean hours",
    },
    distribution: {
      title: "Time to merge",
      subtitle: "How long merged pull requests stayed open, as a share of all merged pull requests.",
      bucket: "Time open",
    },
    scatter: {
      title: "Pull request size and time to merge",
      subtitle: "Each dot is a merged pull request. Both axes use a log scale so small and large changes are visible together.",
      size: "Lines changed",
      openToMerge: "Hours open",
      pr: "Pull request",
    },
    noData: "No data in this range.",
  },

  authors: {
    title: "Authors",
    subtitle: "Pull request activity by author in this range.",
    login: "Author",
    opened: "Opened",
    merged: "Merged",
    medianOpenToMerge: "Median open to merge",
    reviewsGiven: "Reviews given",
    empty: "No authors in this range.",
  },

  prTable: {
    title: "Pull requests",
    subtitle: "Pull requests opened in this range. Select a column heading to sort.",
    number: "Number",
    titleColumn: "Title",
    author: "Author",
    opened: "Opened",
    merged: "Merged",
    openToMerge: "Open to merge",
    firstReview: "First review",
    size: "Lines",
    reviewed: "Reviewed",
    yes: "Yes",
    no: "No",
    notMerged: "Open or closed",
    previous: "Previous page",
    next: "Next page",
    pageOf: (page: number, pages: number) => `Page ${page} of ${pages}`,
    empty: "No pull requests were opened in this range.",
    sortBy: (column: string) => `Sort by ${column}`,
  },

  authorFilter: {
    summary: (included: number, total: number) =>
      included === total ? `All authors (${total})` : included === 0 ? "No authors" : `${included} of ${total} authors`,
    hint: "Untick an author to leave their pull requests out of every figure on this page. Deploys, failure rate and restore time come from workflow runs, so of the DORA measures only lead time changes.",
    all: "All authors",
    none: "No authors",
    legend: "Authors to include",
    opened: (count: number) => (count === 1 ? "1 PR" : `${count} PRs`),
    noneChosen: "Every author is left out, so there is nothing to measure. Choose at least one author from the authors menu.",
  },

  report: {
    download: "Download PDF report",
    hint: "Opens your browser's print dialog. Choose Save as PDF as the destination.",
    prepared: (day: string) => `Report prepared on ${day}`,
    compareSubject: (names: readonly string[]) => names.join(" vs "),
  },

  codeHealth: {
    title: "Code health",
    lede: "How complex the functions in the default branch are, measured on the most recent crawl. This describes the code as it stands and does not follow the date range above.",
    analysedAt: (sha: string, when: string) => `Analysed commit ${sha} on ${when}`,
    loading: "Loading code health",
    medianCcn: "Median complexity",
    medianCcnHint: "The complexity of the middle function. Half the functions are simpler.",
    p75Ccn: "75th percentile complexity",
    p75CcnHint: (max: string) => `Three quarters of functions are at or below this. The most complex function scores ${max}.`,
    shareAbove: (limit: number) => `Functions above ${limit}`,
    shareAboveHint: (high: string, limit: number) => `The share worth a closer look. ${high} are above ${limit}.`,
    nloc: "Lines of code",
    nlocHint: "Lines inside functions, leaving out blank lines and comments.",
    functions: "Functions analysed",
    functionsHint: "Every function the analyser found across all supported languages.",
    staleTitle: "The latest analysis failed",
    stale: (commitDate: string, attemptDate: string, message: string) =>
      `These figures are from the commit dated ${commitDate}. The latest attempt on ${attemptDate} failed with the message "${message}".`,
    explainerTitle: "What cyclomatic complexity means",
    explainer:
      "Cyclomatic complexity counts the independent paths through a function, so each branch, loop or condition adds one. A low score is easy to read and to test. Scores above 10 are worth reviewing and scores above 20 are hard to change safely.",
    chart: {
      title: "Complexity distribution",
      subtitle: "How many functions fall into each complexity band, where a higher score means more paths to test.",
      x: "Cyclomatic complexity",
      series: "Functions",
    },
    hotspots: {
      title: "Most complex functions",
      subtitle: "The functions with the highest complexity, which are the best candidates to simplify first.",
      function: "Function",
      location: "File and line",
      ccn: "Complexity",
      nloc: "Lines",
      empty: "No functions were found.",
    },
    none: {
      title: "Code health has not been measured yet",
      body: "Crawl this repository to clone the default branch and analyse its functions.",
    },
    error: {
      title: "Code health could not be measured",
      install: "To enable it, install lizard with pipx install lizard and crawl the repository again.",
      when: (when: string) => `The last attempt was on ${when}.`,
    },
  },

  repo: {
    loadingTitle: "Loading repository",
    lastCrawled: (when: string) => `Last crawled ${when}`,
    rangeSummary: (from: string, to: string) => `Showing ${from} to ${to}`,
    excludingAuthors: (logins: readonly string[]) =>
      `Leaving out pull requests by ${new Intl.ListFormat("en-GB", { type: "conjunction" }).format(logins)}.`,
    crawlInProgress: "A crawl is in progress, so these figures may still change.",
    notFound: "This repository could not be found.",
  },

  compare: {
    title: "Compare repositories",
    lede: "The same measures for each repository on shared axes. Each repository keeps one colour throughout.",
    needTwo: "Pick at least two repositories to compare.",
    tooMany: "Only the first four repositories are compared.",
    controls: "Comparison options",
    align: "Align to project start",
    alignHint: "Count weeks from each project's first pull request instead of by calendar date.",
    perContributor: "Per contributor",
    perContributorHint: "Divide weekly throughput by the number of people active that week.",
    showPeople: "Show people",
    showPeopleHint: "Off by default so the comparison stays about process rather than individuals.",
    logScale: "Log scale",
    alignedAxis: "Week N since first PR",
    weekN: (n: number) => `Week ${n}`,
    clippedNote: (weeks: number) =>
      `Aligned view is clipped to ${weeks} weeks, the length of the shortest history, so every repository covers the same span.`,
    missing: (count: number) =>
      count === 1 ? "One requested repository could not be found." : `${count} requested repositories could not be found.`,
    headline: {
      title: "Headline figures",
      subtitle: "One column per repository for the selected range.",
      metric: "Measure",
      merged: "PRs merged",
      authors: "Authors",
      authorWeeks: "Author-weeks",
      perAuthorWeek: "Merged per author-week",
      medianSize: "Median PR size (lines)",
      coding: "Median coding time",
      firstReview: "Median time to first review",
      openToMerge: "Median open to merge",
      openToMergeReviewed: "Median open to merge, reviewed",
      openToMergeUnreviewed: "Median open to merge, unreviewed",
      reviewed: "Share reviewed",
      selfMerged: "Share self-merged",
      deploysPerWeek: "Deploys per week",
      leadTime: "Lead time for changes",
      changeFailure: "Change failure rate",
      timeToRestore: "Time to restore",
    },
    cumulative: {
      title: "Cumulative pull requests merged",
      subtitle: "Running total of merged pull requests for each repository.",
      yLabel: "PRs merged to date",
    },
    throughput: {
      title: "Pull requests merged per week",
      titlePerContributor: "Pull requests merged per active author per week",
      subtitle: "Weekly merged pull requests for each repository.",
      subtitlePerContributor: "Weekly merged pull requests divided by the number of people active that week.",
      yLabel: "PRs merged",
      yLabelPerContributor: "PRs merged per author",
    },
    openToMerge: {
      title: "Median open to merge per week",
      subtitle: "The median hours a pull request merged that week spent open.",
      logNote: "Weeks with a zero median are left out on a log scale.",
    },
    distribution: {
      title: "Time to merge distribution",
      subtitle:
        "Share of each repository's merged pull requests in each time bucket, so repositories of different sizes compare fairly.",
    },
    composition: {
      title: "Cycle time composition",
      subtitle: "Mean of the weekly stage means over the range, shown as a share of the whole cycle.",
      noStages: "No merged pull requests with stage data in this range.",
    },
    deploys: {
      title: "Deploys per week",
      subtitle: "Weekly successful production deploys for each repository.",
      yLabel: "Deploys",
    },
    batch: {
      title: "Batch size",
      subtitle: "Lines merged per author-week and median pull request size for each repository.",
      caveat:
        "Lines changed include generated files, lockfiles and vendored code, so treat them as an indication of batch size rather than output.",
      linesPerAuthorWeek: "Lines merged per author-week",
      medianSize: "Median PR size (lines)",
    },
    people: {
      title: "People",
      subtitle: (repo: string) => `Authors in ${repo} for the selected range.`,
    },
    fair: {
      title: "Reading this fairly",
      teamSizes: "Team sizes differ. Authors in this range",
      authorsOf: (repo: string, count: number) => `${repo} ${count === 1 ? "has 1 author" : `has ${count} authors`}`,
      reviewSplit:
        "Reviewed and unreviewed pull requests are shown separately, because a solo author waits for nobody and would otherwise look fast.",
      ages: "Projects of different ages are best compared with Align to project start switched on.",
      overlap:
        "Period all were active compares the same calendar weeks, when every team was working at once; Align to project start compares each project's first weeks instead.",
      leadTime: "Lead time only counts pull requests merged after deploy runs were first observed for that repository.",
      partialWeek:
        "The current week is left off the weekly charts until it ends, so a week only two days old does not look like a slump.",
    },
  },

  states: {
    emptyTitle: "Nothing to show yet",
  },
} as const;

export type Copy = typeof copy;
